name: kamn
description: KAMN Mobile application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-317.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  flutter_spinkit: ^5.1.0
  # mongo
  mongo_dart: ^0.8.1
  #firebase
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_database: ^10.0.5
  cloud_firestore: ^4.0.5
  google_sign_in: ^5.4.2
  firebase_storage: ^11.0.5
  firebase_messaging: ^14.1.0
  firebase_analytics: ^10.0.5
  # database
  sqflite: ^2.2.0+3
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  path: ^1.8.2
  # bloc
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  #styles
  flutter_native_splash: ^2.2.14
  google_fonts: ^3.0.1
  fluttertoast: ^8.1.1
  #widgets
  carousel_slider: ^4.1.1
  flutter_svg: ^1.1.6
  lottie: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.2
  #additinal
  url_launcher: ^6.1.6
  intl: ^0.17.0
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/